### ISSUE TITLE
backend conns be closed when executing 'log @@limit=0,5000' in dble managed port

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#1220]
dble version:  c5a6bb17a1c8cd191894a01046c0d7c13c6740e4

steps:
1. execute in  dble manage port
```
mysql> log @@limit=0,5000;
ERROR 2013 (HY000) :Lost connection to MySQL server during query
```
dble related log:
![image](https://user-images.githubusercontent.com/39580715/58777304-393e0a80-8600-11e9-815b-4e07296e925c.png)

expect result:
return error or correct result instead of closing backend conns

**Comment by sunsun314** [comment]
This case occurs because of the #1171  https://github.com/actiontech/dble/pull/1175
In that PR there are two mistakes  
When try to check the "buffer size is 5",use a remings() function to equals to 5,that means the true condition in default is "buffer size is 2M - 5 bytes".  
This mistakes makes the condition only be true when the large query result be send,such as the "log @@limit..." result  
The other mistake is that use the byteBuffer method array() try to get the byte[] from buffer.But in dble the buffer is all DirectByteBuffer ,this class use native to push and poll the data,which can not be poll by method array()  
In the end, the error occurs when a large query result be sent ,such as  "log @@limit..."

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-67d04aa94d912fb01583096c6d8cba52f513996e-20190619021040
