### ISSUE TITLE
`execute_time`About `show @@ connection.sql` is wrong, sometimes it will < actual execution time of mysql

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1226]
* **dble version：**  
dble-9.9.9.9-d59aaf92252e64fc28d6164755285b0a6303b7ee-20190605023703
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  execute `select sleep(0.1);` in dble and keep the connection on
```
select sleep(0.1);
```
step2. execute `show @@connection.sql` in dble manager port
```
show @@connection.sql;
```
* **expect result：**  
    1. `execute_time` of `show @@ connection.sql` >=100ms
* **real result：**  
    1. sometimes,`execute_time` of `show @@ connection.sql` <100ms
* **supplements：**  
    1.

**Comment by sunsun314** [comment]
Well, that problem is caused by TimeUtil witch store a 20.0xms-changed timestamp. As the timestamp is changed by about 20ms when a fronendConnection start a query at time-20.001ms the timestamp is stored as 20. Then the query is executed successfully and return at time-120.03ms, but the timestamp is still time-100.0xms(Witch would be updated after about 0.0xms).
As a result, the final execute-time printed as 100.0x-20.001 about 80ms

**Comment by sunsun314** [comment]
https://github.com/actiontech/dble-docs-cn/blob/develop/2.Function/2.1_manager_cmd/2.1.03_show.md#21318--show-connectionsql
