### ISSUE TITLE
set autocommit=true problem

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#2873]
* **dble version：**  
dble-3.20.10.x  
dble-3.21.02.x
dble-3.21.06.x
dble-9.9.9.9-c62cbe0589a

* **preconditions ：**  
no
* **configs：** 
not that important for this issue

* **steps：**    
    step1.  connect dble with port 8066, executing sql
```sql
set autocommit=true
```
* **expect result：**  
    1. Query OK
* **real result：**  

![6{F}R4 `R%UPAWT%FC)C~}M](https://user-images.githubusercontent.com/17309012/133743431-cbae134c-1315-49f4-a3f2-763f5d753357.png)
![{}K49JV93DFT`MTLK2CXXYP](https://user-images.githubusercontent.com/17309012/133743587-22a185e8-25b3-4839-be57-4397d079f8ce.png)
<img width="604" alt="Image" src="https://user-images.githubusercontent.com/17309012/133743508-76e4e64d-1f04-4319-95ba-519dac3b04ea.png">

* **supplements：**  
    1. dble-3.20.07.x works well for the set sql, as well as the recently dble-9.9.9.9 
   
![LKYX_Z1$~}@$ 5@H@R( OD](https://user-images.githubusercontent.com/17309012/133743837-52dc180e-6963-4e9c-85e5-26679af1cc94.png)
<img width="648" alt="Image" src="https://user-images.githubusercontent.com/17309012/133743911-7c7836cf-5a49-4074-af0b-16330348a26e.png">

**Comment by Dinosauria** [comment]
**Verified** in
5.7.21-dble-3.21.02.99-7c9bf977c088c1dcc83ebe75aee31a2ba093248f-20210918060452
5.7.21-dble-3.21.06.99-ebe93cc78bd7fba83380c28dca78b09f45046f84-20210917095152
5.7.21-dble-9.9.9.9-a42246facf2e4977cb79812bd8dc9c9fcdde5302-20210917052224
<img width="661" alt="Image" src="https://user-images.githubusercontent.com/17309012/133878601-7be6e07d-c6d8-488e-af59-d98f433eb41b.png">
<img width="674" alt="Image" src="https://user-images.githubusercontent.com/17309012/133878604-34168126-4396-42cc-82ef-dafb960975be.png">
<img width="669" alt="Image" src="https://user-images.githubusercontent.com/17309012/133878607-b9afeaa2-f8f1-48ab-9b66-0a144dbe39a8.png">
**notice**：
the problem not fixed in the version of druid that dble-3.20.10.99 used
3.20.10.99-8b599b2e1753ade38688397eb6183d8e97e037d3-20210917083815
![S29VY_`HKQCF@`824_}P 36](https://user-images.githubusercontent.com/17309012/133878681-fc732c13-3ab1-4c3e-9f5d-910fa75864f7.png)

**Comment by Dinosauria** [comment]
### Problem resolved in -dble-3.20.10.99-8ca3ce
**Verified** in
5.7.21-dble-9.9.9.9-a95b4165300847d8760f9945d7b2f98d38f09a32-20210918060905
5.7.21-dble-3.21.06.99-1c5b5717b1e169e1b67e225018b895b8d76a084f-20210918071503
5.7.21-dble-3.21.02.99-7c9bf977c088c1dcc83ebe75aee31a2ba093248f-20210918060452
5.7.21-dble-3.20.10.99-8ca3ce707e085e174ff9e0fc87574b901aaa50c1-20210918072131

<img width="535" alt="Image" src="https://user-images.githubusercontent.com/17309012/133883691-2e74c38d-cdff-4cd3-9de7-bfbb743b3ff8.png">
<img width="239" alt="Image" src="https://user-images.githubusercontent.com/17309012/133883694-c062d146-cd8f-45d5-aec6-c63b662d5e14.png">
<img width="504" alt="Image" src="https://user-images.githubusercontent.com/17309012/133883757-771b61fa-1b85-4066-8401-b00300e55e08.png">
<img width="255" alt="Image" src="https://user-images.githubusercontent.com/17309012/133883761-208b3c60-0420-41c0-8ab1-f4ad7af6ed89.png">
<img width="490" alt="Image" src="https://user-images.githubusercontent.com/17309012/133883771-d35164e4-31ad-4b41-81c3-d661a677e697.png">
<img width="268" alt="Image" src="https://user-images.githubusercontent.com/17309012/133883779-d05a18d4-de49-448c-979b-cdb7f0823dcd.png">
<img width="504" alt="Image" src="https://user-images.githubusercontent.com/17309012/133883785-f88d3c63-670e-44be-b1ba-71830551a837.png">
<img width="259" alt="Image" src="https://user-images.githubusercontent.com/17309012/133883802-c7e49c1f-63a1-4852-9497-e327c6456634.png">
